# Generated by Django 4.2.3 on 2023-07-10 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utente', '0001_initial'),
        ('stato', '0001_initial'),
        ('caso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fascicolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100, verbose_name='titolo')),
                ('descrizione', models.TextField(verbose_name='descrizione')),
                ('luogo', models.CharField(max_length=100, verbose_name='luogo')),
                ('data', models.DateField(verbose_name='data')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('fkCaso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caso.caso')),
                ('fkStato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stato.stato')),
                ('fkUtente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utente.utente')),
            ],
        ),
    ]
