# Generated by Django 4.2.3 on 2023-07-10 18:39

from django.db import migrations


def create_data(apps, schema_editor):
    ruolo = apps.get_model('ruolo', 'Ruolo')
    ruolo(nome='ADMIN').save()
    ruolo(nome='AUROR').save()
    ruolo(nome='VISITATORE').save()


class Migration(migrations.Migration):

    dependencies = [
        ('ruolo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
