# Generated by Django 4.2.3 on 2023-07-10 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ruolo', '0001_initial'),
        ('utente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtenteRuolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('fkRuolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruolo.ruolo')),
                ('fkUtente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utente.utente')),
            ],
        ),
    ]
