# Generated by Django 4.2.3 on 2023-07-10 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0001_initial'),
    ]

    operations = [
    ]
