# Generated by Django 4.2.3 on 2023-07-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0002_utente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='password',
            field=models.CharField(max_length=100, null=True, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='utente',
            name='username',
            field=models.CharField(max_length=100, null=True, verbose_name='username'),
        ),
    ]
