# Generated by Django 4.2.3 on 2023-07-16 13:11

from django.db import migrations, models
import django.db.models.deletion


def create_data(apps, schema_editor):
    archivio = apps.get_model('archivio', 'Archivio')
    archivio(nome='VISITATORI').save()
    archivio(nome='PROVE').save()
    archivio(nome='BACCHETTE').save()
    archivio(nome='COLLABORATORI').save()


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0002_utente'),
        ('archivio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivio',
            name='fkUtente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utente.utente'),
        ),
        migrations.RunPython(create_data),
    ]
